esphome:
  name: garage-door-test

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:
  reboot_timeout: 0s

esp32:
  board: esp32dev
  framework:
    type: esp-idf

cover:
  - platform: template
    id: "garage_door"
    name: "Garage Door"
    optimistic: true
    assumed_state: false
    open_action:
      - logger.log: "Opening garage door"
    close_action:
      - logger.log: "Closing garage door"
    stop_action:
      - logger.log: "Stopping garage door"

logger:
  level: DEBUG